development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=app_database user=user password=password sslmode=disable
  dir: dbmigrate

test:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=test_database user=user password=password sslmode=disable
  dir: dbmigrate
